const data = {
  // users: [
  //   {
  //     name: 'John',
  //     email: 'admin@example.com',
  //     password: bcrypt.hashSync('123456'),
  //     isAdmin: true,
  //   },
  //   {
  //     name: 'Jane',
  //     email: 'user@example.com',
  //     password: bcrypt.hashSync('123456'),
  //     isAdmin: false,
  //   },
  // ],
  products: [
    {
      name: 'Red bag',
      slug: 'red-bag',
      category: 'Bags',
      image: '/images/bag1.jpg',
      isFeatured: true,
      featuredImage: '/images/banner1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular bag',
    },
    {
      name: 'Green bag',
      slug: 'green-bag',
      category: 'Bags',
      image: '/images/bag2.jpg',
      isFeatured: true,
      featuredImage: '/images/banner2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular bag',
    },
    {
      name: 'Brown bag',
      slug: 'brown-bag',
      category: 'Bags',
      image: '/images/bag3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular bag',
    },
    {
      name: 'Ring 1',
      slug: 'ring-1',
      category: 'Rings',
      image: '/images/ring1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking ring',
    },
    {
      name: 'Ring 2',
      slug: 'ring-2',
      category: 'Rings',
      image: '/images/ring2.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking ring',
    },
    {
      name: 'Ring 3',
      slug: 'ring-3',
      category: 'Rings',
      image: '/images/ring3.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking ring',
    },
    {
      name: 'Popular shoes',
      slug: 'popular-shoes',
      category: 'Shoes',
      image: '/images/shoes1.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shoes',
    },
    {
      name: 'Girl shoes',
      slug: 'girl-shoes',
      category: 'Shoes',
      image: '/images/shoes2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A girl shoes',
    },
    {
      name: 'White shoes',
      slug: 'white-shoes',
      category: 'Shoes',
      image: '/images/shoes3.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A white shoes',
    },
    {
      name: 'Black watch',
      slug: 'black-watch',
      category: 'Watch',
      image: '/images/watch1.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A black watch',
    },
    {
      name: 'Gold watch',
      slug: 'black-watch',
      category: 'Watch',
      image: '/images/watch2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A black watch',
    },
    {
      name: 'Brown watch',
      slug: 'brown-watch',
      category: 'Watch',
      image: '/images/watch3.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A black watch',
    },
  ],
};
export default data;